
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} host=database sslmode=disable"
      DEBUG: true
      HOST: ":4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
        interval: 1s
        timeout: 1s
        retries: 60
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine3.21
    ports:
     - 80:80
    volumes:
     - ./nginx:/etc/nginx/templates
    depends_on:
      web:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    command: ["-source=file://migrations", "-database",  "postgres://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}?sslmode=disable", "up"]
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    depends_on:
      database:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - --web.route-prefix=/prometheus
      - --web.external-url=http://localhost:9090/prometheus
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090"]
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 40s 
    depends_on:
      web:
        condition: service_healthy

volumes:
  database-data:
